---
name: Reviewdog
on:
  workflow_call:
permissions: {}
concurrency:
  group: reviewdog-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  ##############################################################################
  # Matrix
  ##############################################################################
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      targets: ${{ steps.matrix.outputs.result }}
    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: v2.55.1
    - name: Generate Matrix
      id: matrix
      run: echo "result=$(task reviewdog:matrix)" >> "$GITHUB_OUTPUT"
    - name: Check Matrix
      env:
        REVIEWDOG_MATRIX: ${{ steps.matrix.outputs.result }}
      run: |-
        echo "${REVIEWDOG_MATRIX}" | jq
  ##############################################################################
  # Runner
  ##############################################################################
  reviewdog:
    needs: matrix
    name: Reviewdog (${{ matrix.name }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.targets) }}
    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: v2.55.1
        aqua_opts: -t reviewdog,${{ matrix.target }}
    - name: Setup reporter
      id: reporter
      run: |-
        case "${{ github.event_name }}" in
        "push" )                echo "type=github-check" >> "$GITHUB_OUTPUT" ;;
        "pull_request" )        echo "type=github-pr-review" >> "$GITHUB_OUTPUT" ;;
        "pull_request_target" ) echo "type=github-pr-review" >> "$GITHUB_OUTPUT" ;;
        * )                     echo "type=local" >> "$GITHUB_OUTPUT" ;;
        esac
    - name: Running reviewdog
      run: task "${REVIEWDOG_TARGET}"
      env:
        REVIEWDOG_TARGET: ${{ matrix.target }}
        REVIEWDOG_REPORTER: ${{ steps.reporter.outputs.type }}
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REVIEWDOG_ARGS: -log-level 'debug' -tee
